name: Deploy to Hugging Face

on:
  push:
    branches:
      - main  # or whatever your default branch name is

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://LucasPlant:$HF_TOKEN@huggingface.co/spaces/LucasPlant/controlsim
          git push --force space main:main
